### ISSUE TITLE
kamailio - architecture with only registrar (audio codec and webrtc)

### ISSUE THREAD

**Issue by yboujraf** [davidcsi/kamailio-private-public#9]
Dear @davidcsi 

# My architecture :

I have the same architecture except I am not using any pbx central (freepbx, freeswitch, asterisk, ...) and between the public and private network I have a firewall (pFsense).

Kamailio server has one or two NIC. Depends of the setup, If two NIC, because the security engineer doesn't want to connect to the DMZ the audio codec or webrtc users on the private network.

- DB and RTPEngine :

Actually one DB and one rtpengine but would like to have a cluster for redundancy for each one.

![sipsecure](https://user-images.githubusercontent.com/6151258/88002484-ecb6d680-cb02-11ea-8a85-e4755f1facbf.png)

- Audio codec & webrtc :

I use today :

-  audio codec ( softphone - audio codec from telecom companies mayah, tieline, digiram, aeta, ...) 

- webrtc using web apps to chats and using video.

Each audio codec and webrtc client has a login/psswd (from Kamailio - registrar).

It will be great if we could collaborate.  I have posted some issues to identify my requests.
I am able to test anything with you.

Best regards,
Youssef

**Comment by davidcsi** [comment]
Hello,

Sure, i'll take a look asap.

David
